name: "winecellar"
description: "On, Hekyll! On, Jekyll! On Huginn and Muninn!"

source: ./template
destination: ./www

port: 0xd16a
url: http://winecellar.com

serve:
  - ./www

marked:
  gfm: true
  tables: true
  breaks: false
  pedantic: false
  sanitize: true
  smartLists: true
  smartypants: false

plugins:
  - huginn-asset-bundler

asset_bundler:
  compress:
    js: false
    css: false
  base_path: /assets/
  shim: /winecellar
  dev: true
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'></script>
"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />
"
